2019-12-30 22:26:12.510  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDBPool.<init>(PhysicalDBPool.java:127)) - total resources of dataHost dbserver1 is :1
2019-12-30 22:26:12.514  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDBPool.<init>(PhysicalDBPool.java:127)) - total resources of dataHost dbserver2 is :1
2019-12-30 22:26:12.514  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDBPool.<init>(PhysicalDBPool.java:127)) - total resources of dataHost localhost1 is :1
2019-12-30 22:26:12.555  INFO [WrapperSimpleAppMain] (io.mycat.cache.CacheService.createLayeredPool(CacheService.java:125)) - create layer cache pool TableID2DataNodeCache of type encache ,default cache size 10000 ,default expire seconds18000
2019-12-30 22:26:12.558  INFO [WrapperSimpleAppMain] (io.mycat.cache.DefaultLayedCachePool.createChildCache(DefaultLayedCachePool.java:80)) - create child Cache: TESTDB_ORDERS for layered cache TableID2DataNodeCache, size 50000, expire seconds 18000
2019-12-30 22:26:13.126  INFO [WrapperSimpleAppMain] (io.mycat.config.classloader.DynaClassLoader.<init>(DynaClassLoader.java:34)) - dyna class load from .\catlet,and auto check for class file modified every 60 seconds
2019-12-30 22:26:13.198  INFO [WrapperSimpleAppMain] (io.mycat.MycatServer.startup(MycatServer.java:314)) - MyCat is ready to startup ...
2019-12-30 22:26:13.198  INFO [WrapperSimpleAppMain] (io.mycat.MycatServer.startup(MycatServer.java:326)) - Startup processors ...,total processors:8,aio thread pool size:16    
 each process allocated socket buffer pool  bytes ,a page size:2097152  a page's chunk number(PageSize/ChunkSize) is:512  buffer page's number is:160
2019-12-30 22:26:13.198  INFO [WrapperSimpleAppMain] (io.mycat.MycatServer.startup(MycatServer.java:327)) - sysconfig params:SystemConfig [processorBufferLocalPercent=100, frontSocketSoRcvbuf=1048576, frontSocketSoSndbuf=4194304, backSocketSoRcvbuf=4194304, backSocketSoSndbuf=1048576, frontSocketNoDelay=1, backSocketNoDelay=1, maxStringLiteralLength=65535, frontWriteQueueSize=2048, bindIp=0.0.0.0, serverPort=8066, managerPort=9066, charset=utf8, processors=8, processorExecutor=16, timerExecutor=2, managerExecutor=2, idleTimeout=1800000, catletClassCheckSeconds=60, sqlExecuteTimeout=300, processorCheckPeriod=1000, dataNodeIdleCheckPeriod=300000, dataNodeHeartbeatPeriod=10000, clusterHeartbeatUser=_HEARTBEAT_USER_, clusterHeartbeatPass=_HEARTBEAT_PASS_, clusterHeartbeatPeriod=5000, clusterHeartbeatTimeout=10000, clusterHeartbeatRetry=10, txIsolation=3, parserCommentVersion=50148, sqlRecordCount=10, bufferPoolPageSize=2097152, bufferPoolChunkSize=4096, bufferPoolPageNumber=160, maxResultSet=524288, bigResultSizeSqlCount=10, bufferUsagePercent=80, flowControlRejectStrategy=0, clearBigSqLResultSetMapMs=600000, defaultMaxLimit=100, sequnceHandlerType=2, sqlInterceptor=io.mycat.server.interceptor.impl.DefaultSqlInterceptor, sqlInterceptorType=select, sqlInterceptorFile=E:\Arms\mycat/logs/sql.txt, mutiNodeLimitType=0, mutiNodePatchSize=100, defaultSqlParser=druidparser, usingAIO=0, packetHeaderSize=4, maxPacketSize=16777216, mycatNodeId=1]
2019-12-30 22:26:13.436  INFO [WrapperSimpleAppMain] (io.mycat.MycatServer.startup(MycatServer.java:436)) - using nio network handler 
2019-12-30 22:26:13.672  INFO [WrapperSimpleAppMain] (io.mycat.MycatServer.startup(MycatServer.java:452)) - $_MyCatManager is started and listening on 9066
2019-12-30 22:26:13.685  INFO [WrapperSimpleAppMain] (io.mycat.MycatServer.startup(MycatServer.java:456)) - $_MyCatServer is started and listening on 8066
2019-12-30 22:26:13.686  INFO [WrapperSimpleAppMain] (io.mycat.MycatServer.startup(MycatServer.java:458)) - ===============================================
2019-12-30 22:26:13.686  INFO [WrapperSimpleAppMain] (io.mycat.MycatServer.startup(MycatServer.java:462)) - Initialize dataHost ...
2019-12-30 22:26:13.687  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDBPool.initSource(PhysicalDBPool.java:389)) - init backend mysql source ,create connections total 10 for hostM1 index :0
2019-12-30 22:26:13.689  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 1381084174 ,create new connection for hostM1 of schema eim2 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:26:13.690  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 1381084174 ,create new connection for hostM1 of schema eim2 totalConnectionCount: 0 increamentCount: 2
2019-12-30 22:26:13.690  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 1381084174 ,create new connection for hostM1 of schema eim2 totalConnectionCount: 0 increamentCount: 3
2019-12-30 22:26:13.690  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 1381084174 ,create new connection for hostM1 of schema eim2 totalConnectionCount: 0 increamentCount: 4
2019-12-30 22:26:13.691  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 1381084174 ,create new connection for hostM1 of schema eim2 totalConnectionCount: 0 increamentCount: 5
2019-12-30 22:26:13.691  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 1381084174 ,create new connection for hostM1 of schema eim2 totalConnectionCount: 0 increamentCount: 6
2019-12-30 22:26:13.691  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 1381084174 ,create new connection for hostM1 of schema eim2 totalConnectionCount: 0 increamentCount: 7
2019-12-30 22:26:13.691  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 1381084174 ,create new connection for hostM1 of schema eim2 totalConnectionCount: 0 increamentCount: 8
2019-12-30 22:26:13.692  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 1381084174 ,create new connection for hostM1 of schema eim2 totalConnectionCount: 0 increamentCount: 9
2019-12-30 22:26:13.692  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 1381084174 ,create new connection for hostM1 of schema eim2 totalConnectionCount: 0 increamentCount: 10
2019-12-30 22:26:34.988 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:34.988  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:34.988  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:26:34.988  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:34.988 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:34.988  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:34.988  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:26:34.988  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:35.004 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:35.004  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:35.004  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:26:35.004  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:35.004 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:35.004  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:35.005  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:26:35.005  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:35.005 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:35.005  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:35.005  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:26:35.005  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:35.042 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:35.042  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:35.042  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:26:35.043  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:35.118 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:35.118  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:35.118  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:26:35.119  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:35.119 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:35.119  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:35.119  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:26:35.119  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:35.153 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:35.153  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:35.153  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:26:35.153  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:35.308 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:35.308  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:35.308  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:26:35.308  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:35.333  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDBPool.initSource(PhysicalDBPool.java:414)) - init result :finished 10 success 0 target count:10
2019-12-30 22:26:35.333 ERROR [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDBPool.init(PhysicalDBPool.java:374)) - #!MyCat#dbserver1 init failure
2019-12-30 22:26:35.333  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDBPool.initSource(PhysicalDBPool.java:389)) - init backend mysql source ,create connections total 10 for hostM1 index :0
2019-12-30 22:26:35.333  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 614635279 ,create new connection for hostM1 of schema eim3 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:26:35.334  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 614635279 ,create new connection for hostM1 of schema eim3 totalConnectionCount: 0 increamentCount: 2
2019-12-30 22:26:35.334  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 614635279 ,create new connection for hostM1 of schema eim3 totalConnectionCount: 0 increamentCount: 3
2019-12-30 22:26:35.334  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 614635279 ,create new connection for hostM1 of schema eim3 totalConnectionCount: 0 increamentCount: 4
2019-12-30 22:26:35.334  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 614635279 ,create new connection for hostM1 of schema eim3 totalConnectionCount: 0 increamentCount: 5
2019-12-30 22:26:35.335  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 614635279 ,create new connection for hostM1 of schema eim3 totalConnectionCount: 0 increamentCount: 6
2019-12-30 22:26:35.335  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 614635279 ,create new connection for hostM1 of schema eim3 totalConnectionCount: 0 increamentCount: 7
2019-12-30 22:26:35.336  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 614635279 ,create new connection for hostM1 of schema eim3 totalConnectionCount: 0 increamentCount: 8
2019-12-30 22:26:35.337  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 614635279 ,create new connection for hostM1 of schema eim3 totalConnectionCount: 0 increamentCount: 9
2019-12-30 22:26:35.338  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 614635279 ,create new connection for hostM1 of schema eim3 totalConnectionCount: 0 increamentCount: 10
2019-12-30 22:26:56.394 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:56.394  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:56.395  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:26:56.395  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:56.395 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:56.395  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:56.395  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:26:56.395  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:56.396 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:56.396  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:56.396  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:26:56.396  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:56.396 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:56.396  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:56.397  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:26:56.397  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:56.397 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:56.397  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:56.397  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:26:56.397  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:56.397 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:56.397  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:56.398  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:26:56.398  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:56.398 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:56.398  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:56.399  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:26:56.399  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:56.399 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:56.399  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:56.399  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:26:56.399  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:56.399 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:56.400  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:56.400  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:26:56.400  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:56.400 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:56.401  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:56.401  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:26:56.401  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:56.482  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDBPool.initSource(PhysicalDBPool.java:414)) - init result :finished 10 success 0 target count:10
2019-12-30 22:26:56.483 ERROR [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDBPool.init(PhysicalDBPool.java:374)) - #!MyCat#dbserver2 init failure
2019-12-30 22:26:56.483  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDBPool.initSource(PhysicalDBPool.java:389)) - init backend mysql source ,create connections total 10 for hostM1 index :0
2019-12-30 22:26:56.483  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:26:56.483  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 2
2019-12-30 22:26:56.484  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 3
2019-12-30 22:26:56.484  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 4
2019-12-30 22:26:56.484  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 5
2019-12-30 22:26:56.484  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 6
2019-12-30 22:26:56.484  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 7
2019-12-30 22:26:56.484  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 8
2019-12-30 22:26:56.484  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 9
2019-12-30 22:26:56.484  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 10
2019-12-30 22:26:58.514 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:58.514  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:58.514  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection refused: no further information
2019-12-30 22:26:58.514  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:58.514 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:58.514  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:58.514  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection refused: no further information
2019-12-30 22:26:58.514  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:58.514 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:58.514  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:58.514  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection refused: no further information
2019-12-30 22:26:58.514  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:58.514 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:58.514  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:58.514  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection refused: no further information
2019-12-30 22:26:58.514  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:58.514 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:58.514  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:58.514  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection refused: no further information
2019-12-30 22:26:58.514  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:58.514 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:58.514  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:58.514  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection refused: no further information
2019-12-30 22:26:58.514  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:58.514 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:58.514  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:58.514  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection refused: no further information
2019-12-30 22:26:58.518  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:58.518 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:58.518  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:58.518  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection refused: no further information
2019-12-30 22:26:58.518  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:58.534 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:58.534  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:58.534  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection refused: no further information
2019-12-30 22:26:58.534  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:58.535 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:26:58.535  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:26:58.535  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:74)) - connect error MySQLConnection [id=0, lastTime=1577715972545, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]java.lang.Throwable: java.net.ConnectException: Connection refused: no further information
2019-12-30 22:26:58.535  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:26:58.582  INFO [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDBPool.initSource(PhysicalDBPool.java:414)) - init result :finished 10 success 0 target count:10
2019-12-30 22:26:58.582 ERROR [WrapperSimpleAppMain] (io.mycat.backend.datasource.PhysicalDBPool.init(PhysicalDBPool.java:374)) - #!MyCat#localhost1 init failure
2019-12-30 22:26:58.763  INFO [Timer0] (io.mycat.backend.datasource.PhysicalDatasource.createByIdleLitte(PhysicalDatasource.java:397)) - create connections ,because idle connection not enough ,cur is 0, minCon is 10 for hostM1
2019-12-30 22:26:58.780  INFO [Timer0] (io.mycat.backend.datasource.PhysicalDatasource.createByIdleLitte(PhysicalDatasource.java:397)) - create connections ,because idle connection not enough ,cur is 0, minCon is 10 for hostM1
2019-12-30 22:26:58.780  INFO [Timer0] (io.mycat.backend.datasource.PhysicalDatasource.createByIdleLitte(PhysicalDatasource.java:397)) - create connections ,because idle connection not enough ,cur is 0, minCon is 10 for hostM1
2019-12-30 22:26:58.782  INFO [WrapperSimpleAppMain] (io.mycat.MycatServer.startup(MycatServer.java:502)) - ===============================================
2019-12-30 22:26:58.782  INFO [WrapperSimpleAppMain] (io.mycat.MycatServer.startup(MycatServer.java:503)) - Perform XA recovery log ...
2019-12-30 22:26:58.783  INFO [WrapperSimpleAppMain] (io.mycat.MycatServer.startup(MycatServer.java:507)) - Perform XA recovery log end...
2019-12-30 22:26:58.784  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 1381084174 ,create new connection for hostM1 of schema eim2 totalConnectionCount: 0 increamentCount: 11
2019-12-30 22:26:58.784  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 614635279 ,create new connection for hostM1 of schema eim3 totalConnectionCount: 0 increamentCount: 11
2019-12-30 22:26:58.784  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 11
2019-12-30 22:27:00.817 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:27:00.818  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716018782, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:27:00.818  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:27:00.819 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 1  DBHostConfig [hostName=hostM1, url=127.0.0.1:3306]
2019-12-30 22:27:00.819  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:27:00.820 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:27:00.820  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716018739, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:27:00.820  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.NewConnectionRespHandler.connectionError(NewConnectionRespHandler.java:37)) - MySQLConnection [id=0, lastTime=1577716018739, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] connectionError java.lang.Throwable: java.net.ConnectException: Connection refused: no further information
2019-12-30 22:27:00.820  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:27:00.821 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:27:00.821  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716018739, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:27:00.821  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.NewConnectionRespHandler.connectionError(NewConnectionRespHandler.java:37)) - MySQLConnection [id=0, lastTime=1577716018739, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] connectionError java.lang.Throwable: java.net.ConnectException: Connection refused: no further information
2019-12-30 22:27:00.822  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:27:00.822 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:27:00.822  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716018739, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:27:00.822  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.NewConnectionRespHandler.connectionError(NewConnectionRespHandler.java:37)) - MySQLConnection [id=0, lastTime=1577716018739, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] connectionError java.lang.Throwable: java.net.ConnectException: Connection refused: no further information
2019-12-30 22:27:00.822  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:27:08.751  INFO [Timer0] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:27:10.799 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:27:10.799  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716028735, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:27:10.799  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:27:10.799 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 2  DBHostConfig [hostName=hostM1, url=127.0.0.1:3306]
2019-12-30 22:27:10.799  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:27:18.759  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:27:19.815 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:27:19.815  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577716018782, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:27:19.815  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:27:19.815 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 1  DBHostConfig [hostName=hostM1, url=10.30.100.105:3306]
2019-12-30 22:27:19.815  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:27:19.815 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:27:19.815  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577716018739, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:27:19.815  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.NewConnectionRespHandler.connectionError(NewConnectionRespHandler.java:37)) - MySQLConnection [id=0, lastTime=1577716018739, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] connectionError java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:27:19.815  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:27:19.815 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:27:19.815  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577716018739, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:27:19.815  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.NewConnectionRespHandler.connectionError(NewConnectionRespHandler.java:37)) - MySQLConnection [id=0, lastTime=1577716018739, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] connectionError java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:27:19.815  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:27:19.815 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:27:19.815  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577716018739, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:27:19.815  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.NewConnectionRespHandler.connectionError(NewConnectionRespHandler.java:37)) - MySQLConnection [id=0, lastTime=1577716018739, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] connectionError java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:27:19.815  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:27:19.815 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:27:19.815  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577716018739, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:27:19.815  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.NewConnectionRespHandler.connectionError(NewConnectionRespHandler.java:37)) - MySQLConnection [id=0, lastTime=1577716018739, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] connectionError java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:27:19.815  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:27:19.815 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:27:19.815  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577716018739, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:27:19.815  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.NewConnectionRespHandler.connectionError(NewConnectionRespHandler.java:37)) - MySQLConnection [id=0, lastTime=1577716018739, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] connectionError java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:27:19.815  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:27:19.815 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:27:19.815  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577716018782, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:27:19.815  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:27:19.815 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 1  DBHostConfig [hostName=hostM1, url=10.30.100.106:3306]
2019-12-30 22:27:19.815  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:27:19.815 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:27:19.815  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577716018739, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:27:19.815  WARN [$_NIOConnector] (io.mycat.backend.mysql.nio.handler.NewConnectionRespHandler.connectionError(NewConnectionRespHandler.java:37)) - MySQLConnection [id=0, lastTime=1577716018739, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] connectionError java.lang.Throwable: java.net.ConnectException: Connection timed out: no further information
2019-12-30 22:27:19.815  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:27:20.829 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:27:20.829  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716038759, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:27:20.830  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:27:21.102  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:27:28.756  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 1381084174 ,create new connection for hostM1 of schema eim2 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:27:28.756  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 614635279 ,create new connection for hostM1 of schema eim3 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:27:28.756  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:27:30.821 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:27:30.822  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716048756, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:27:30.823  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:27:30.823 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 1  DBHostConfig [hostName=hostM1, url=127.0.0.1:3306]
2019-12-30 22:27:30.823  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:27:38.750  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:27:40.792 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:27:40.792  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716058750, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:27:40.792  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:27:40.792 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 2  DBHostConfig [hostName=hostM1, url=127.0.0.1:3306]
2019-12-30 22:27:40.792  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:27:48.749  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:27:49.813 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:27:49.813  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577716048756, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:27:49.813  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:27:49.813 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 2  DBHostConfig [hostName=hostM1, url=10.30.100.105:3306]
2019-12-30 22:27:49.813  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:27:49.814 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:27:49.814  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577716048756, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:27:49.814  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:27:49.814 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 2  DBHostConfig [hostName=hostM1, url=10.30.100.106:3306]
2019-12-30 22:27:49.814  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:27:50.797 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:27:50.797  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716068734, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:27:50.797  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:27:50.797  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:27:58.746  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 1381084174 ,create new connection for hostM1 of schema eim2 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:27:58.746  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 614635279 ,create new connection for hostM1 of schema eim3 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:27:58.747  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:28:00.789 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:28:00.789  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716078746, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:28:00.789  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:28:00.789 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 1  DBHostConfig [hostName=hostM1, url=127.0.0.1:3306]
2019-12-30 22:28:00.789  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:28:08.758  INFO [Timer0] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:28:10.830 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:28:10.830  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716088758, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:28:10.830  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:28:10.830 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 2  DBHostConfig [hostName=hostM1, url=127.0.0.1:3306]
2019-12-30 22:28:10.831  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:28:18.767  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:28:19.807 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:28:19.807  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577716078746, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:28:19.807  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:28:19.834  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:28:19.834 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:28:19.834  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577716078746, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:28:19.834  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:28:19.958  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:28:20.806 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:28:20.806  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716098767, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:28:20.806  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:28:20.807  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:28:28.758  INFO [Timer0] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 1381084174 ,create new connection for hostM1 of schema eim2 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:28:28.758  INFO [Timer0] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 614635279 ,create new connection for hostM1 of schema eim3 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:28:28.759  INFO [Timer0] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:28:30.798 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:28:30.799  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716108758, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:28:30.799  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:28:30.799 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 1  DBHostConfig [hostName=hostM1, url=127.0.0.1:3306]
2019-12-30 22:28:30.799  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:28:38.747  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:28:40.801 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:28:40.802  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716118747, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:28:40.802  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:28:40.802 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 2  DBHostConfig [hostName=hostM1, url=127.0.0.1:3306]
2019-12-30 22:28:40.802  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:28:48.759  INFO [Timer0] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:28:49.800 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:28:49.800  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577716108758, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:28:49.800  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:28:49.800 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 1  DBHostConfig [hostName=hostM1, url=10.30.100.105:3306]
2019-12-30 22:28:49.801  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:28:49.801 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:28:49.801  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577716108758, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:28:49.802  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:28:49.802 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 1  DBHostConfig [hostName=hostM1, url=10.30.100.106:3306]
2019-12-30 22:28:49.802  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:28:50.798 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:28:50.799  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716128759, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:28:50.799  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:28:50.799  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:28:58.753  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 1381084174 ,create new connection for hostM1 of schema eim2 totalConnectionCount: 1 increamentCount: 0
2019-12-30 22:28:58.753  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 614635279 ,create new connection for hostM1 of schema eim3 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:28:58.753  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:29:00.803 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:29:00.803  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716138753, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:29:00.804  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:29:00.804 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 1  DBHostConfig [hostName=hostM1, url=127.0.0.1:3306]
2019-12-30 22:29:00.804  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:29:08.765  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:29:10.812 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:29:10.812  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716148765, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:29:10.812  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:29:10.812 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 2  DBHostConfig [hostName=hostM1, url=127.0.0.1:3306]
2019-12-30 22:29:10.812  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:29:18.761  INFO [Timer0] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:29:19.816 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:29:19.816  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577716138753, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:29:19.816  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:29:19.816 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 2  DBHostConfig [hostName=hostM1, url=10.30.100.106:3306]
2019-12-30 22:29:19.816  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:29:19.818 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:29:19.818  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577716138753, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:29:19.818  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:29:19.818 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 2  DBHostConfig [hostName=hostM1, url=10.30.100.105:3306]
2019-12-30 22:29:19.818  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:29:20.810 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:29:20.810  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716158761, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:29:20.810  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:29:20.811  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:29:28.757  INFO [Timer0] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 1381084174 ,create new connection for hostM1 of schema eim2 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:29:28.757  INFO [Timer0] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 614635279 ,create new connection for hostM1 of schema eim3 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:29:28.757  INFO [Timer0] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:29:30.789 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:29:30.789  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716168757, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:29:30.789  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:29:30.789 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 1  DBHostConfig [hostName=hostM1, url=127.0.0.1:3306]
2019-12-30 22:29:30.789  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:29:38.745  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:29:40.753 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:29:40.754  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716178733, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:29:40.754  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:29:40.754 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 2  DBHostConfig [hostName=hostM1, url=127.0.0.1:3306]
2019-12-30 22:29:40.755  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:29:48.746  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:29:49.771 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:29:49.771  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577716168757, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:29:49.771  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:29:49.771  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:29:49.787 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:29:49.787  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577716168757, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:29:49.787  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:29:49.787  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:29:50.750 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:29:50.750  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716188734, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:29:50.750  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:29:50.750  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:29:58.747  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 1381084174 ,create new connection for hostM1 of schema eim2 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:29:58.747  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 614635279 ,create new connection for hostM1 of schema eim3 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:29:58.747  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:30:00.752 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:30:00.753  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716198734, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:30:00.753  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:30:00.753 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 1  DBHostConfig [hostName=hostM1, url=127.0.0.1:3306]
2019-12-30 22:30:00.753  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:30:08.745  INFO [Timer0] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:30:10.751 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:30:10.752  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716208733, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:30:10.752  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:30:10.752 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 2  DBHostConfig [hostName=hostM1, url=127.0.0.1:3306]
2019-12-30 22:30:10.752  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:30:18.761  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:30:19.756 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:30:19.757  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577716198734, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:30:19.757  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:30:19.757 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 1  DBHostConfig [hostName=hostM1, url=10.30.100.106:3306]
2019-12-30 22:30:19.758  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:30:19.758 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:30:19.758  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577716198734, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:30:19.759  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:30:19.759 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 1  DBHostConfig [hostName=hostM1, url=10.30.100.105:3306]
2019-12-30 22:30:19.759  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:30:20.792 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:30:20.792  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716218761, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:30:20.792  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:30:20.793  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:30:28.764  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 1381084174 ,create new connection for hostM1 of schema eim2 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:30:28.764  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 614635279 ,create new connection for hostM1 of schema eim3 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:30:28.764  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:30:30.816 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:30:30.816  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716228764, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:30:30.817  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:30:30.817 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 1  DBHostConfig [hostName=hostM1, url=127.0.0.1:3306]
2019-12-30 22:30:30.817  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:30:38.750  INFO [Timer1] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:30:40.812 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:30:40.812  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716238734, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:30:40.812  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:30:40.812 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 2  DBHostConfig [hostName=hostM1, url=127.0.0.1:3306]
2019-12-30 22:30:40.813  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:30:48.752  INFO [Timer0] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:30:49.797 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:30:49.797  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577716228764, user=root, schema=eim3, old shema=eim3, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.106, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:30:49.797  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:30:49.798 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 2  DBHostConfig [hostName=hostM1, url=10.30.100.106:3306]
2019-12-30 22:30:49.798  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:30:49.798 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:30:49.798  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection timed out: no further information ,MySQLConnection [id=0, lastTime=1577716228764, user=root, schema=eim2, old shema=eim2, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=10.30.100.105, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:30:49.798  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:30:49.799 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 2  DBHostConfig [hostName=hostM1, url=10.30.100.105:3306]
2019-12-30 22:30:49.799  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:30:50.817 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:30:50.817  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716248734, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:30:50.818  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:30:50.818  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
2019-12-30 22:30:58.746  INFO [Timer0] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 1381084174 ,create new connection for hostM1 of schema eim2 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:30:58.746  INFO [Timer0] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 614635279 ,create new connection for hostM1 of schema eim3 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:30:58.746  INFO [Timer0] (io.mycat.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:564)) - no ilde connection in pool 269501044 ,create new connection for hostM1 of schema eim1 totalConnectionCount: 0 increamentCount: 1
2019-12-30 22:31:00.757 ERROR [$_NIOConnector] (io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:155)) - error:
java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:164) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.finishConnect(NIOConnector.java:143) ~[Mycat-server-1.6.7.3-release.jar:?]
	at io.mycat.net.NIOConnector.run(NIOConnector.java:98) ~[Mycat-server-1.6.7.3-release.jar:?]
2019-12-30 22:31:00.757  INFO [$_NIOConnector] (io.mycat.net.AbstractConnection.close(AbstractConnection.java:520)) - close connection,reason:java.net.ConnectException: Connection refused: no further information ,MySQLConnection [id=0, lastTime=1577716258733, user=root, schema=eim1, old shema=eim1, borrowed=false, fromSlaveDB=false, threadId=0, charset=utf8, txIsolation=3, autocommit=true, attachment=null, respHandler=null, host=127.0.0.1, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-12-30 22:31:00.757  INFO [$_NIOConnector] (io.mycat.sqlengine.SQLJob.connectionError(SQLJob.java:125)) - can't get connection for sql :select user()
2019-12-30 22:31:00.757 ERROR [$_NIOConnector] (io.mycat.backend.heartbeat.MySQLHeartbeat.nextDector(MySQLHeartbeat.java:215)) - set Error 1  DBHostConfig [hostName=hostM1, url=127.0.0.1:3306]
2019-12-30 22:31:00.757  INFO [$_NIOConnector] (io.mycat.backend.datasource.PhysicalDatasource$1$1.connectionError(PhysicalDatasource.java:508)) - connection connectionError 
